pipeline {
    agent any
    stages {
        //stage('Build') {
        //    agent {
        //        docker {
        //            image 'node:22.19.0-alpine'
        //            reuseNode true
        //            args '-v jenkins-data:/var/jenkins_home'
        //        }
        //    }
        //    steps {
        //        sh '''
        //            ls -la
        //            node --version
        //            npm --version
        //            npm install
        //            npm run build
        //            ls -la
        //        '''
        //    }
        //}
        //stage('Test') {
        //    agent {
        //        docker {
        //            image 'node:22.19.0-alpine'
        //            reuseNode true
        //            args '-v jenkins-data:/var/jenkins_home'
        //        }
        //    }
        //    steps {
        //        sh '''
        //            test -f build/index.html
        //            CI=true npm test
        //        '''
        //    }
        //}
        stage('AWS') {
            agent {
                docker {
                    image 'amazon/aws-cli:2.34.14'
                    reuseNode true
                    args '--entrypoint=""'
                }
            }
            steps {
                withCredentials([usernamePassword(credentialsId: 'reactcicdtemp', passwordVariable: 'WS_SECRET_ACCESS_KEY', usernameVariable: 'WS_ACCESS_KEY_ID')]) {
                // some block
}
                    sh '''
                        aws --version
                        aws s3 ls
                    '''
                }
            }
        }
    }
}